### ISSUE TITLE
Tags List View

### ISSUE THREAD

**Issue by tiaradwiputri** [teamalgoritma/algoritmablog#16]
Providing the tags list will be useful for people heading to the blog with a topic in mind.
Something like:
https://algotech.netlify.com/tags/ should be accessible from the home for easier navigation.

![image](https://user-images.githubusercontent.com/8868527/77145117-3d1d1980-6aba-11ea-8b92-e28921683901.png)

*PS: I refer LSTM blog post on my previous NN class, while the post itself is on the first page of the blog (hard to find)

**Comment by ahmadhusain** [comment]
Thank you. Great input for user experience enhancement. I have added *article list* menu on the blog homepage. 

![image](https://user-images.githubusercontent.com/33796928/77231395-3af7af80-6bcd-11ea-946f-107dd07b08af.png)
